### ISSUE TITLE
Spacing of individual entries 

### ISSUE THREAD

**Issue by nkferraiolo** [waynegraham/hidden_collections_registry#13]
Is it possible to display data after the summary in two columns? This would make each entry more compact and have less wasted space. 

See example: https://hcregistry.herokuapp.com/projects/763

**Comment by waynegraham** [comment]
It is straight forward to do this. I wonder if something like this display might be more useful though:

https://spotlight.dlme.clir.org/library/catalog/stanford_tk780vf9050

If you do want two columns, could you let me know which fields you want in which column?

**Comment by nkferraiolo** [comment]
I'm not sure that the the model of the template in the link is necessary, since we only have one thumbnail per entry. 

If we were to have two columns, perhaps we could have Grant Type, Year Awarded, Address, and Primary contact in one column, and Format, Size, Date Range, and Geographic scope in the other. This would separate the general information for the project from the information on the collections.
