### ISSUE TITLE
Distinguish between CHC and DHC recipients 

### ISSUE THREAD

**Issue by nkferraiolo** [waynegraham/hidden_collections_registry#2]
Perhaps we should add a field called "grant program," so that people can tell which program funded the project. I think this would be useful because 1) Mellon cares about the distinction, 2) people familiar with the digitization program might be confused by the descriptions for the cataloging projects, 3) It allows us room to grow, if we ever want to add RAR for future programs to this.

**Comment by waynegraham** [comment]
There is a `program` field in the database that I believe was meant for this information. I can add this to the show view, but at some later point we could do something more interesting on the browse pages to visually distinguish the two.

**Comment by nkferraiolo** [comment]
Sounds like a plan!

**Comment by waynegraham** [comment]
I've manually updated this on the server side to have this data.
