### ISSUE TITLE
New fields to add 

### ISSUE THREAD

**Issue by nkferraiolo** [waynegraham/hidden_collections_registry#5]
Project website
Repositories (this is for DHC projects only)

**Comment by waynegraham** [comment]
The project website already exists (`project_url`). 

Is the repository a url as well? (e.g. `repository_url`) or some other kind of information?

**Comment by nkferraiolo** [comment]
Yes! The repository will be a URL, although most of these won't be available until the projects are completed. This would be a field I imagine may be added manually by the Program Associate/Assistant after final reports are submitted.
