### ISSUE TITLE
Thumbnails? 

### ISSUE THREAD

**Issue by nkferraiolo** [waynegraham/hidden_collections_registry#8]
Is the plan still for this to ultimately replace our funded projects page of the DHC website? If so, we'll want to add a place for thumbnail images for each project. Next year, I hope to have a question on the application form requiring that applicants submit them, so we should have better luck tracking them down than we have over the past three years. 

Note: We currently have images for the 2008-2013 grantees, and we can assign images for 2015-2016 from the samples they've included in their applications. The only group that doesn't have images at the moment are the 2014 grantees, which would require some emailing, but wouldn't be that difficult to find.

**Comment by waynegraham** [comment]
Is this something we need now, or something we can kick down the road a bit?

Where are the images, I don't know enough information about these to even estimate how much effort would be required to implement this.

**Comment by nkferraiolo** [comment]
This is definitely something we can kick down the road.  This can be added after we share with Mellon and even after we go live.

Here’s where the images are now, but we only have them for our 2008-2013 grantees.
https://www.clir.org/hiddencollections/awards/for-2013

We can make them for 2015-2016 from the images they provided in the application.

**Comment by waynegraham** [comment]
@nkferraiolo can I close this ticket?

**Comment by nkferraiolo** [comment]
Yes! So long as we remember to add the 2014-2016 ones later.
